### ISSUE TITLE
Invalid package requires error handling

### ISSUE THREAD

**Issue by rejeep** [cask/epl#28]
Calling `epl-package-from-file` on a file with an invalid `Package-Requires` header, for example

```
;; Package-Requires: ((s "1.7.0") (dash "2.2.0")
```

will result in the error `End of file during parsing`. This error can be very difficult to track in packages using EPL.

I suggest handling the error in EPL and raise a proper error in such case.

See https://github.com/cask/cask/issues/284

**Comment by lunaryorn** [comment]
@rejeep I've added better error handling.  Would you mind to test that with Cask?

**Comment by rejeep** [comment]
@lunaryorn Seems to be working great, thanks!
