### ISSUE TITLE
Tag for version 0.8 has strange name

### ISSUE THREAD

**Issue by spwhitton** [cask/epl#30]
Version 0.8 is tagged `71d8098` instead of `0.8`.  Please tag this commit as `0.8`.  Thanks.

**Comment by lunaryorn** [comment]
@spwhitton Sorry :cry:  What a blunder of mine :angry:

I've replaced the broken tag with a proper 0.8 tag.  Thanks for reporting, please check whether the new tag is correct :relaxed:

**Comment by spwhitton** [comment]
Yup, all good now, thanks!

Sean
