### ISSUE TITLE
Support package-archive-priorities

### ISSUE THREAD

**Issue by Silex** [cask/epl#32]
Hello,

@fommil at https://github.com/Silex/package-utils/issues/4 reported an issue that I think is in fact an epl issue :wink: 

Basically, `epl-find-upgrades` (and thus `epl-upgrade`) ignores `package-archive-priorities` and always finds the latest version from all archives.

It apparently has the effect that upgrading packages through epl has not the same effect as upgrading packages from `package-list-package`.

That being said, I'm not entirely sure my description above is accurate, but it's what it feels like.

If you point me to the right direction I can make a PR.

**Comment by lunaryorn** [comment]
I wasn't aware that EPL was used anywhere outside Cask for this purpose.  Cask doesn't support archive priorities (yet?) and so EPL does neither.

I do not have time to implement this, so I'd appreciate a PR.  Look at `epl-find-upgrades` and compare it to what package.el does wrt `package-archive-priorities`.  You'll essentially have to reimplement package.el's behaviour here.

Note though that it's slightly more subtle than just throwing out archives of lower priorities.  In particular package.el sticks to the archive a package was installed from, i.e. if you explicitly install a package from a lower-prio archive package.el will start to consider that archive for upgrades of the package.

**Comment by Silex** [comment]
> I wasn't aware that EPL was used anywhere outside Cask for this purpose. Cask doesn't support archive priorities (yet?) and so EPL does neither.

Hehe, I gave some hints in https://github.com/cask/epl/pull/26 when I mentionned my repo.

> I do not have time to implement this, so I'd appreciate a PR. Look at epl-find-upgrades and compare it to what package.el does wrt package-archive-priorities. You'll essentially have to reimplement package.el's behaviour here.
>
> Note though that it's slightly more subtle than just throwing out archives of lower priorities. In particular package.el sticks to the archive a package was installed from, i.e. if you explicitly install a package from a lower-prio archive package.el will start to consider that archive for upgrades of the package.

I'll see what I can do, I realised that maybe it is simpler to actually do what package.el do about upgrades (display the packages in a hidden buffer, mark the upgrades, get the list of upgrades).

**Comment by Silex** [comment]
Closing for #33

**Comment by laurynas-biveinis** [comment]
It seems that this was closed because of https://github.com/cask/epl/pull/33, which never got completed. Should this be re-opened then? It looks like a valid request, see e.g. a downstream issue at https://github.com/xuchunyang/epm/issues/6
