### ISSUE TITLE
(file-error "http://stable.melpa.org/packages/epl-0.8.el" "Not found") 

### ISSUE THREAD

**Issue by gaurav-sood** [cask/epl#37]
I am getting this error whenever I try to install helm-projectile or for that matter any package that requires epl.

(file-error "http://stable.melpa.org/packages/epl-0.8.el" "Not found")

**Comment by sambrightman** [comment]
epl 0.9 was released and I don’t think MELPA Stable keeps old versions. I’m not sure if anything is wrong here or if they just need to move their dependency forward. I thought in most situations people specified a minimum rather than exact version.

**Comment by sambrightman** [comment]
`pkg-info` is probably the underlying dependency. Issues should be filed with the packages you are having problems with unless installation succeeds with stock Emacs and fails with Cask.

That said, `helm-projectile` installs just fine for me (on Emacs 25.3), correctly grabbing the new epl 0.9. Have you perhaps not updated your package list?

**Comment by gaurav-sood** [comment]
it is resolved. I am not sure how :)
